name: portfolio-deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on:
      labels: [self-hosted, maverick-dousec]
    steps:
      - uses: actions/checkout@v6
      - run: bun install --frozen-lockfile
      - run: bun run build
      - uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
      - run: rsync -av --delete --chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r dist/ /opt/gh/www/dousec.org/
      - uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: success
          env: production
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://dousec.org
